/**
  * Created by louie on 3/2/2017.
  */
class classes {

}

case class NYPDCrime(
                      UniqueKey: Int,
                      CreatedDate: String,
                      ClosedDate: String,
                      Agency: String,
                      AgencyName: String,
                      ComplaintType: String,
                      Descriptor: String,
                      LocationType: String,
                      IncidentZip: String,
                      IncidentAddress: String,
                      StreetName: String,
                      CrossStreet1: String,
                      CrossStreet2: String,
                      IntersectionStreet1: String,
                      IntersectionStreet2: String,
                      AddressType: String,
                      City: String,
                      Landmark: String,
                      FacilityType: String,
                      Status: String,
                      DueDate: String,
                      ResolutionActionUpdatedDate: String,
                      CommunityBoard: String,
                      Borough: String,
                      XCoordinate: String,
                      YCoordinate: String,
                      ParkFacilityName: String,
                      ParkBorough: String,
                      SchoolName: String,
                      SchoolNumber: String,
                      SchoolRegion: String,
                      SchoolCode: String,
                      SchoolPhoneNumber: String,
                      SchoolAddress: String,
                      SchoolCity: String,
                      SchoolState: String,
                      SchoolZip: String,
                      SchoolNotFound: String,
                      SchoolorCitywideComplaint: String,
                      VehicleType: String,
                      TaxiCompanyBorough: String,
                      TaxiPickUpLocation: String,
                      BridgeHighwayName: String,
                      BridgeHighwayDirection: String,
                      RoadRamp: String,
                      BridgeHighwaySegment: String,
                      GarageLotName: String,
                      FerryDirection: String,
                      FerryTerminalName: String,
                      Latitude: String,
                      Longitude: String,
                      Location: String)
